spring:
  application:
     name: a-bootiful-web-client
     
  datasource:
    url: jdbc:mysql://localhost/micro
    username: root
    password: root
  jpa:
    generate-ddl: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
   
  client:    
    serviceUrl:
      defaultZone: http://localhost:4004/eureka
    
server:
  port: 0 
  
logging:
  level: 
    httpclient.wire: DEBUG